/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uddk.view;

import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uddk.controller.LoginController;
import uddk.controller.MainPageController;

/**
 *
 * @author USER
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form Mainpage
     */
    private String username;

    public MainPage(String username) {
        initComponents();
        initTBRoom();
        initCBRoomType();
        initCBRoomCap();
        this.username = username;
        checkUserPrivilege();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    private void initTBRoom() {
        Vector data = MainPageController.getAllRoomForTable();
        tbRoom.setModel(new DefaultTableModel((Vector) data.get(0), (Vector) data.get(1)) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }

    public void updateTBRoom(Vector data) {
        tbRoom.setModel(new DefaultTableModel((Vector) data.get(0), (Vector) data.get(1)) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }

    private void initCBRoomType() {
        Vector data = MainPageController.getAllUniqueRoomType();
        data.insertElementAt("", 0);
        cbRoomType.setModel(new DefaultComboBoxModel(data));
    }

    private void initCBRoomCap() {
        Vector data = MainPageController.getAllUniqueRoomCapacity();
        data.insertElementAt("", 0);
        cbRoomCap.setModel(new DefaultComboBoxModel(data));
    }

    

    

    private void checkUserPrivilege() {
        this.btDeviceManager.setVisible(LoginController.isAdmin(username));
        this.btUserManager.setVisible(LoginController.isAdmin(username));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btRegisteredRoom = new javax.swing.JButton();
        btDeviceManager = new javax.swing.JButton();
        btUserManager = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRoom = new javax.swing.JTable();
        cbRoomCap = new javax.swing.JComboBox<>();
        cbRoomType = new javax.swing.JComboBox<>();
        btSearch = new javax.swing.JButton();
        btRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Thông tin phòng");

        btRegisteredRoom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btRegisteredRoom.setText("Thông tin phòng đã đăng ký");
        btRegisteredRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisteredRoomActionPerformed(evt);
            }
        });

        btDeviceManager.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btDeviceManager.setText("Quản lý thiết bị");
        btDeviceManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeviceManagerActionPerformed(evt);
            }
        });

        btUserManager.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btUserManager.setText("Quản lý người dùng");
        btUserManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserManagerActionPerformed(evt);
            }
        });

        tbRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã phòng", "Loại phòng", "Sức chứa"
            }
        ));
        jScrollPane1.setViewportView(tbRoom);

        cbRoomCap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sức chứa", "90", "80", "70" }));

        cbRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại phòng", "Lý thuyết", "Thực hành" }));

        btSearch.setText("Tìm kiếm");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        btRegister.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btRegister.setText("Đăng ký");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btDeviceManager, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(267, 267, 267))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btRegisteredRoom)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btUserManager, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btRegister)
                        .addContainerGap(688, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(cbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(cbRoomCap, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUserManager, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRegisteredRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDeviceManager, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRoomCap, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(cbRoomType, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        String type = cbRoomType.getSelectedItem().toString();
        String cap = cbRoomCap.getSelectedItem().toString();
        Vector data = MainPageController.filterRoom(type, cap);
        updateTBRoom(data);
    }//GEN-LAST:event_btSearchActionPerformed

    private void btDeviceManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeviceManagerActionPerformed
        new DeviceManager(username);
        this.dispose();


    }//GEN-LAST:event_btDeviceManagerActionPerformed

    private void btUserManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserManagerActionPerformed
        new UserManager(username);
        this.dispose();
    }//GEN-LAST:event_btUserManagerActionPerformed

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
        if (tbRoom.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Please select at least one record!", "Invalid room", 0);
        } else {
            String roomCode = tbRoom.getValueAt(tbRoom.getSelectedRow(), 0).toString();
            new RegisterRoom(this, true, roomCode, username);
        }


    }//GEN-LAST:event_btRegisterActionPerformed

    private void btRegisteredRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisteredRoomActionPerformed
        new RoomRegistered(username);
        this.dispose();
    }//GEN-LAST:event_btRegisteredRoomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDeviceManager;
    private javax.swing.JButton btRegister;
    private javax.swing.JButton btRegisteredRoom;
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btUserManager;
    private javax.swing.JComboBox<String> cbRoomCap;
    private javax.swing.JComboBox<String> cbRoomType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbRoom;
    // End of variables declaration//GEN-END:variables
}
