/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uddk.view;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uddk.controller.ReportController;

/**
 *
 * @author USER
 */
public class ReportList extends javax.swing.JFrame {

    /**
     * Creates new form ListReport
     */
    private String username;

    public ReportList(String username) {
        initComponents();
        this.username = username;
        initTBReport();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public void initTBReport() {
        Vector data = ReportController.getAllReportDataForTable();
        tbReport.setModel(new DefaultTableModel((Vector) data.get(0), (Vector) data.get(1)) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btRegistered = new javax.swing.JButton();
        btDeviceManager = new javax.swing.JButton();
        btUserManager = new javax.swing.JButton();
        btRoom = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbReport = new javax.swing.JTable();
        btReportDetail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Danh sách báo cáo");

        btRegistered.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btRegistered.setText("Thông tin phòng đã đăng ký");
        btRegistered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisteredActionPerformed(evt);
            }
        });

        btDeviceManager.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btDeviceManager.setText("Quản lý thiết bị");
        btDeviceManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeviceManagerActionPerformed(evt);
            }
        });

        btUserManager.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btUserManager.setText("Quản lý người dùng");
        btUserManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserManagerActionPerformed(evt);
            }
        });

        btRoom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btRoom.setText("Thông tin phòng");
        btRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRoomActionPerformed(evt);
            }
        });

        tbReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã báo cáo", "Ngày báo cáo", "Mã giáo viên", "Mã phòng", "Thời gian", "Vấn đề", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(tbReport);

        btReportDetail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btReportDetail.setText("Thông tin chi tiết");
        btReportDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReportDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btRegistered)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(btDeviceManager, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btUserManager, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btReportDetail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(278, 278, 278))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btRegistered, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btDeviceManager, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btUserManager, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btReportDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btReportDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReportDetailActionPerformed
        if (tbReport.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Please select at least one record!", "Invalid user", 0);
        } else {
            String reportId = tbReport.getValueAt(tbReport.getSelectedRow(), 0).toString();
            new ReportDetail(this, rootPaneCheckingEnabled, reportId, this);
        }
    }//GEN-LAST:event_btReportDetailActionPerformed

    private void btRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRoomActionPerformed
        new MainPage(username);
        this.dispose();
    }//GEN-LAST:event_btRoomActionPerformed

    private void btRegisteredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisteredActionPerformed
        new RoomRegistered(username);
        this.dispose();
    }//GEN-LAST:event_btRegisteredActionPerformed

    private void btDeviceManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeviceManagerActionPerformed
        new DeviceManager(username);
        this.dispose();
    }//GEN-LAST:event_btDeviceManagerActionPerformed

    private void btUserManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserManagerActionPerformed
        new UserManager(username);
        this.dispose();
    }//GEN-LAST:event_btUserManagerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDeviceManager;
    private javax.swing.JButton btRegistered;
    private javax.swing.JButton btReportDetail;
    private javax.swing.JButton btRoom;
    private javax.swing.JButton btUserManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbReport;
    // End of variables declaration//GEN-END:variables
}
